# Generated by Django 2.2.3 on 2019-09-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=None, upload_to='skills'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='image',
            field=models.ImageField(default='21.jpg', upload_to='works'),
        ),
    ]
