# Generated by Django 2.2.3 on 2019-09-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.TextField(default=0, verbose_name='Devicon'),
            preserve_default=False,
        ),
    ]
